Repository kubernetes-sigs/gwctl, pull requests merged in 2024-09, with the labels that each got.

#5 Initialize repository with commits from gateway-api
  .gitignore
  Makefile
  README.md
  cmd/analyze/analyze.go
  cmd/apply/apply.go
  cmd/delete/delete.go
  cmd/get/get.go
  cmd/root.go
  go.mod
  go.sum
  images/example-graph.png
  main.go
  pkg/common/clients.go
  pkg/common/errors.go
  pkg/common/factory.go
  pkg/common/testhelpers.go
  pkg/common/types.go
  pkg/extension/directlyattachedpolicy/directlyattachedpolicy.go
  pkg/extension/extensions.go
  pkg/extension/gatewayeffectivepolicy/gatewayeffectivepolicy.go
  pkg/extension/notfoundrefvalidator/notfoundrefvalidator.go
  pkg/extension/refgrantvalidator/refgrantvalidator.go
  pkg/extension/utils/utils.go
  pkg/flags/flags.go
  pkg/policymanager/helpers.go
  pkg/policymanager/manager.go
  pkg/policymanager/merger.go
  pkg/policymanager/merger_test.go
  pkg/printer/backends.go
  pkg/printer/backends_test.go
  pkg/printer/gatewayclasses.go
  pkg/printer/gatewayclasses_test.go
  pkg/printer/gateways.go
  pkg/printer/gateways_test.go
  pkg/printer/httproutes.go
  pkg/printer/httproutes_test.go
  pkg/printer/main_test.go
  pkg/printer/namespace.go
  pkg/printer/namespace_test.go
  pkg/printer/policies.go
  pkg/printer/policies_test.go
  pkg/printer/printer.go
  pkg/printer/utils.go
  pkg/printer/utils_test.go
  pkg/topology/gateway/gateway.go
  pkg/topology/gateway/graphviz.go
  pkg/topology/graph.go
  pkg/topology/graph_test.go
  pkg/topology/utils.go
  pkg/version/version.go
  test/example/crds.yaml
  test/example/examples.yaml
  test/integration/get_test.go
  test/integration/main_test.go
  test/integration/testdata/sample1.yaml
  test/integration/utils.go
Labels: approved, cncf-cla: yes, size/XXL, lgtm

#7 Correct formatting in github alerts in README.md
  README.md
Labels: approved, cncf-cla: yes, size/XS, lgtm

#8 fix: Use gwctl directory in README instead of gateway-api
  README.md
Labels: approved, cncf-cla: yes, size/XS, lgtm

#9 Add skeleton 'verify' scripts and 'test' Makefile target for presubmits
  Makefile
  hack/verify-all.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
Labels: approved, cncf-cla: yes, size/L, lgtm
